### ISSUE TITLE
Support Xamarin Forms in Android Eumulator 

### ISSUE THREAD

**Issue by JimSEOW** [xamarin/Workbooks#16]
To start workbook in Eumulator, we need 
`var mainActivity = StartedActivities.First();`

To initiate Xamarin.Forms in Android, we need
`Xamarin.Forms.Forms.Init (context, bundle);`

```
	public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
	{
		protected override void OnCreate (Bundle bundle)
		{
			TabLayoutResource = Resource.Layout.Tabbar;
			ToolbarResource = Resource.Layout.Toolbar; 

			base.OnCreate (bundle);

			global::Xamarin.Forms.Forms.Init (this, bundle);
			LoadApplication (new App ());
		}
	}
```

==> Is there a way to make Xamarin.Forms.Platform.Android to work in Workbook and Android Emulator???

**Comment by sandyarmstrong** [comment]
Hello Jim. This repository is just for hosting sample Workbooks, not for providing support or filing Workbooks bugs.

You can get Workbooks support here: https://forums.xamarin.com/categories/inspector

That being said, you cannot create subclasses of Java types in Workbooks right now (https://bugzilla.xamarin.com/show_bug.cgi?id=45382), so you cannot create custom `Activity` classes.

However, in the case of Xamarin.Forms, if you add the NuGet package to your workbook, the workbook app in the emulator switches over to a Xamarin.Forms Android Activity. You will see it in `StartedActivities`.

If you have further questions, please follow up in the forums, thanks!
