### ISSUE TITLE
Error in pasting a python code into the document section

### ISSUE THREAD

**Issue by JimSEOW** [xamarin/Workbooks#17]
Please follow the discussion [here](https://forums.xamarin.com/discussion/comment/277419#Comment_277419)

https://forums.xamarin.com/discussion/comment/277419#Comment_277419
![xamarin workbooks_2017-05-30_23-17-30](https://cloud.githubusercontent.com/assets/8244633/26605465/67103a64-458e-11e7-9b42-3e9cbf0aa03c.png)

Attempting to save this results in error
![xamarin workbooks_2017-05-30_23-26-01](https://cloud.githubusercontent.com/assets/8244633/26605733/6875eab0-458f-11e7-8c2b-aa25033b26d4.png)

**Comment by sandyarmstrong** [comment]
https://forums.xamarin.com/discussion/comment/277421

**Comment by terrencejames** [comment]
Hi, I'd like to ask how was this issue closed/resolve? I'm experiencing the same issue on the latest version.

**Comment by sandyarmstrong** [comment]
@terrencejames For now, I'd recommend doing that kind of markdown editing in a text editor (the `.workbook` is just a markdown file).

**Comment by terrencejames** [comment]
> @terrencejames For now, I'd recommend doing that kind of markdown editing in a text editor (the `.workbook` is just a markdown file).

@sandyarmstrong this would be fine, but the problem is I want a non-executable block of C# code (not inline). If I use ``` without specifying a language it will not render correctly, I have to specify csharp formatting but at that point Xamarin Workbooks parses this as making the code block executable. I hope this can be addressed in a future release, thank you for the fast reply :)
