### ISSUE TITLE
Console, Terminal workbooks?

### ISSUE THREAD

**Issue by juanfranblanco** [xamarin/Workbooks#2]
Currently there is a dependency (as far as I know) to have iOS, Android or WPF player. I love the idea of workbooks, but is there going to be a cross platform version to teach apis?

My scenario: 
I have this Ethereum api for .net, which frankly needs a better help as users might not be familiar with Ethereum https://github.com/Nethereum/Nethereum.

A part from the usual read the docs, documentation, I would like a step by step instructions on how to interact with the API using workbooks, or even better have 1 single source and output to both.

Further down the line, of course it is ideal to provide UI examples (to demonstrate portability) like here: https://github.com/Nethereum/Nethereum.UI.Wallet.Sample

**Comment by tmds** [comment]
@juanfranblanco Looking for .NET Core workbook, would probably solve your use case as well

**Comment by juanfranblanco** [comment]
Yes that would do the trick 😃

**Comment by tmds** [comment]
Being able to run this on Linux would be awesome as well.

**Comment by sandyarmstrong** [comment]
We now have a "Console" workbook type in 0.99.0.
