### ISSUE TITLE
ListView example for Android is really for iOS

### ISSUE THREAD

**Issue by KristofferBerge** [xamarin/Workbooks#25]
https://github.com/xamarin/Workbooks/blob/master/xamarin-forms/user-interface/listview/ListView1-android.workbook

The example contains the same code and import as the iOS workbook

**Comment by sandyarmstrong** [comment]
These samples are out-of-date. No platform-specific code should be necessary in them. You do not need to set up your own XF app instance; we do that for you automatically now.

**Comment by bojanrajkovic** [comment]
I threw together a quick update of this particular sample at https://gist.github.com/bojanrajkovic/4dda9934c6abb83d576ad3886b4a87b8, but Sandy's right, the Forms samples should all be updated. :)

**Comment by atsushieno** [comment]
The sample didn't work, HTTPS request fails. I assume it is due to recent github changes wrt TLS 1.2 and Android not handling TLS 1.2 until recently. But I would like to check with the Android team first.

**Comment by atsushieno** [comment]
Actually it is heisenbug - it works on my machine too.
