### ISSUE TITLE
Change Return key behaviour to never evaluate a cell when pressed without modifiers

### ISSUE THREAD

**Issue by rcarmo** [xamarin/Workbooks#28]
As outlined in the [documentation](https://docs.microsoft.com/en-us/xamarin/tools/workbooks/keybindings), pressing the Return key at the end of a cell submits the cell for evaluation.

I've found this to be at odds with the behaviour of other Workbook/notebook interfaces I use regularly (i.e., Jupyter and DataBricks/Zeppelin), and to be an annoyance when I'm iterating on a cell and am trying to add a newline to insert a new instruction.

Given that I've been using notebook UIs since Mathematica came along, I would suggest that the expectation that Return by itself does _not_ evaluate a cell is not just an ingrained habit, but a hallowed tradition of sorts.

**Comment by sandyarmstrong** [comment]
Thanks for filing! Would you mind moving this to https://github.com/Microsoft/workbooks ? That is the main repository for Workbooks. xamarin/workbooks is just for samples.

If you don't get a chance I can move it for you later today.

**Comment by rcarmo** [comment]
Done.
