### ISSUE TITLE
Crashing bug on Windows

### ISSUE THREAD

**Issue by mrlacey** [xamarin/Workbooks#4]
Using version 0.99.1.1 on Windows 10.0.14393

Repro:

- Create a new Console workbook
- Select `View Inspector` from the tabs at the bottom
- Tap the `select a view` button from the top of the screen
- CRASH!

![workbookscrash](https://cloud.githubusercontent.com/assets/189547/20185873/9f2c2972-a722-11e6-9c09-bc2bcb253960.png)

Suspect the issue is that View Inspector doesn't make sense (apply) for console apps.

**Comment by sandyarmstrong** [comment]
This is fixed in the upcoming release.
