### ISSUE TITLE
Excruciating performance issues using MoreLINQ

### ISSUE THREAD

**Issue by atifaziz** [xamarin/Workbooks#6]
If a create a blank workbook and reference the [MoreLINQ package](https://www.nuget.org/packages/morelinq/2.0.0) then Xamarin Workbooks becomes excruciating slow, with almost 20 seconds of pauses between each keystroke.

I'm using Xamarin Workbooks 1.0 on Windows 10 version 1511. The next section assumes the same environment.

## Steps to Reproduce

1. Create a blank workbook
2. Press <kbd>CTRL</kbd> + <kbd>G</kbd> to bring up the Package Manager
3. Enter `morelinq` in the **Search NuGet** field.
4. Select **morelinq 2.0.0** from the list of matching packages
5. Click **Add Package**
6. Previous step should add an executable C# cell with the code `#r "MoreLinq"`; press <kbd>SHIFT</kbd> + <kbd>ENTER</kbd> at the end of the reference to add new code

At the last step and every keystroke beyond, I'm seeing 20 second pauses between each keystroke!

You can also load the following workbook to try instead of running steps 1-5 manually ([also attached as Test.workbook.zip](https://github.com/xamarin/Workbooks/files/678545/Test.workbook.zip)):

    ---
    uti: com.xamarin.workbook
    platforms:
    - Console
    packages:
    - id: morelinq
      version: 2.0.0
    ---

    ```csharp
    #r "MoreLinq"
    ```

**Comment by atifaziz** [comment]
I tested the same steps on Xamarin Workbooks 1.0 on a macOS Sierra 10.12.2 and there was no performance problem whatsoever. However, testing on a second Windows 10 box exhibited the issue in the opening comment.

**Comment by bojanrajkovic** [comment]
Hi, this should be fixed in our most recent Windows versions. Can you update to Workbooks 1.2.1 and see if the symptoms persist there?

**Comment by sandyarmstrong** [comment]
Closing, as this should be fixed. Feel free to re-open if it's not.

If you encounter any more bugs, please file them [in our bugzilla](https://bugzilla.xamarin.com/enter_bug.cgi?product=Workbooks%20%26%20Inspector). Thanks for the report, and sorry for the delayed response!

**Comment by atifaziz** [comment]
@bojanrajkovic @sandyarmstrong I just got round to testing with the latest version and thought I'd let you know that it works like a charm. :tada: Thanks and keep up the awesome work!
