### ISSUE TITLE
Export to Markdown with code output

### ISSUE THREAD

**Issue by atifaziz** [xamarin/Workbooks#7]
It would be cool to have an option to export a workbook as a snapshot Markdown document where the output of the code blocks is embedded into the exported version. This will enable workbook authors to maintain a single master and then generate an exported version for people using devices or platforms where Xamarin Workbooks is not supported. I understand that this may only make sense for console-type of workbooks.

**Comment by sandyarmstrong** [comment]
Sorry for the late response, we typically only look for Workbooks bug reports on Xamarin bugzilla (this repo is just for samples).

This is on our roadmap, though I have no estimate for when we will get to it. Definitely something that will make it nicer to share workbooks online.

**Comment by migueldeicaza** [comment]
This feature is being tracked elsehwere, the issues here are about the actual workbooks.

**Comment by atifaziz** [comment]
@migueldeicaza Do you have to link to where the feature is being tracked?

**Comment by sandyarmstrong** [comment]
@atifaziz it is currently tracked in our team's internal trello board. You are welcome to file a feature request [in bugzilla](https://bugzilla.xamarin.com/enter_bug.cgi?product=Workbooks%20%26%20Inspector) if you want something public to track.
