### ISSUE TITLE
Missing Line in Learning iOS Workbook

### ISSUE THREAD

**Issue by DavidBrower** [xamarin/Workbooks#8]
In [line 74](https://github.com/xamarin/Workbooks/blob/master/ios/getting-started/Learning-iOS.workbook#L74) of Learning-iOS.workbook there appears to be a line missing. When it mentions passing the view controller into the navigation controller it says:

> If you inspect the simulator, it should look like this:

However, it doesn't say how it should look.

It then says

> * ⚠️This step is important. If you don’t do this step, the rest of the code may not work correctly

Unfortunately, I am not able to get past this step as I am clearly not doing something right.

**Comment by sandyarmstrong** [comment]
Yes, you are meant to add some code yourself in order to proceed.

Also, the "it should look like this" line has been removed.
